# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  host: localhost
  database: app_development

test:
  <<: *default
  host: localhost
  database: app_test

production:
  <<: *default
  host: localhost
  database: app_production
  username: admin
  password: kept2017
